

"""
Multi-Agent Review Dashboard

PHASE-3 EXTENSION: Unified human-in-the-loop review interface.
Tabs: SDR | Sales | Negotiation | Finance

BACKWARD COMPATIBILITY:
- SDR tab preserves exact Phase-2 functionality
- New tabs add-only, no modifications to existing workflow
"""

import streamlit as st
from pathlib import Path
import sys

# Ensure project root is importable
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from db.db_handler import (
    # SDR functions (Phase-2 unchanged)
    fetch_pending_reviews,
    mark_review_decision,
    
    # Sales functions (Phase-3 new)
    fetch_pending_deal_reviews,
    mark_deal_decision,
    
    # Negotiation functions (Phase-3 new)
    fetch_pending_contract_reviews,
    mark_contract_decision,
    
    # Finance functions (Phase-3 new)
    fetch_pending_dunning_reviews,
    mark_dunning_decision
)

import pandas as pd


# Page config
st.set_page_config(
    page_title="Revo – Multi-Agent Review Panel",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
<style>
    .stTabs [data-baseweb="tab-list"] button [data-testid="stMarkdownContainer"] p {
        font-size: 20px;
        font-weight: 600;
    }
    .review-card {
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        background-color: #f9f9f9;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.title("🧠 Revo – Human-in-the-Loop Review Dashboard")
st.markdown("Review AI-generated content across the entire sales pipeline.")

# Create tabs for each agent
tab1, tab2, tab3, tab4 = st.tabs(["📧 SDR Emails", "💼 Sales Qualifications", "🤝 Negotiations", "💰 Finance/Dunning"])


# ==============================================================================
# TAB 1: SDR EMAIL REVIEW (PHASE-2 UNCHANGED)
# ==============================================================================

with tab1:
    st.header("SDR Email Drafts")
    st.markdown("Review cold outreach emails generated by the SDR Agent.")
    
    # Fetch BOTH Pending + Structural Failed
    pending_sdr = fetch_pending_reviews(include_structural_failed=True)
    
    if pending_sdr.empty:
        st.success("✅ No pending SDR reviews")
    else:
        st.info(f"📊 {len(pending_sdr)} emails pending review")
        
        for _, row in pending_sdr.iterrows():
            with st.container():
                col1, col2 = st.columns([3, 1])
                
                with col1:
                    st.subheader(f"Lead: {row['name']} ({row['company']})")
                
                with col2:
                    # Status badge
                    if row["review_status"] == "STRUCTURAL_FAILED":
                        st.error("❌ Validation Failed")
                    else:
                        score = row.get("confidence_score", 0)
                        if score >= 85:
                            st.warning("🟡 Near Auto-Approval")
                        else:
                            st.info("🔵 Needs Review")
                
                # Lead details
                col_a, col_b, col_c = st.columns(3)
                with col_a:
                    st.metric("Role", row.get('role', 'N/A'))
                with col_b:
                    st.metric("Industry", row.get('industry', 'N/A'))
                with col_c:
                    st.metric("Score", f"{row.get('confidence_score', 0)}/100")
                
                # Email editor
                edited_email = st.text_area(
                    "Email Draft",
                    value=row["draft_message"],
                    height=250,
                    key=f"sdr_email_{row['id']}"
                )
                
                # Action buttons
                btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                
                with btn_col1:
                    if st.button("✅ Approve & Send", key=f"sdr_approve_{row['id']}"):
                        mark_review_decision(row["id"], "Approved", edited_email)
                        st.success("Approved!")
                        st.rerun()
                
                with btn_col2:
                    if st.button("❌ Reject", key=f"sdr_reject_{row['id']}"):
                        mark_review_decision(row["id"], "Rejected", edited_email)
                        st.warning("Rejected")
                        st.rerun()
                
                st.markdown("---")


# ==============================================================================
# TAB 2: SALES QUALIFICATION REVIEW (PHASE-3 NEW)
# ==============================================================================

with tab2:
    st.header("Sales Qualification Assessments")
    st.markdown("Review BANT scoring and deal qualification notes.")
    
    try:
        pending_deals = fetch_pending_deal_reviews()
        
        if pending_deals.empty:
            st.success("✅ No pending sales reviews")
        else:
            st.info(f"📊 {len(pending_deals)} deals pending review")
            
            for _, deal in pending_deals.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        st.subheader(f"Deal #{deal['deal_id']} - Lead ID: {deal['lead_id']}")
                    
                    with col2:
                        score = deal.get('qualification_score', 0)
                        if score >= 85:
                            st.success(f"🟢 Score: {score}/100")
                        elif score >= 70:
                            st.warning(f"🟡 Score: {score}/100")
                        else:
                            st.error(f"🔴 Score: {score}/100")
                    
                    # Deal metrics
                    col_a, col_b, col_c = st.columns(3)
                    with col_a:
                        st.metric("Stage", deal.get('stage', 'N/A'))
                    with col_b:
                        st.metric("Deal Value", f"${deal.get('acv', 0):,}")
                    with col_c:
                        st.metric("BANT Score", f"{deal.get('qualification_score', 0)}/100")
                    
                    # Qualification notes
                    st.text_area(
                        "Qualification Assessment",
                        value=deal.get('notes', ''),
                        height=200,
                        key=f"sales_notes_{deal['deal_id']}",
                        disabled=True  # Read-only
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve Deal", key=f"sales_approve_{deal['deal_id']}"):
                            mark_deal_decision(deal['deal_id'], "Approved")
                            st.success("Deal approved - moved to Proposal Sent!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject Deal", key=f"sales_reject_{deal['deal_id']}"):
                            mark_deal_decision(deal['deal_id'], "Rejected")
                            st.warning("Deal rejected")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading sales reviews: {e}")


# ==============================================================================
# TAB 3: NEGOTIATION REVIEW (PHASE-3 NEW)
# ==============================================================================

with tab3:
    st.header("Negotiation Strategies")
    st.markdown("Review objection handling and proposed solutions.")
    
    try:
        pending_contracts = fetch_pending_contract_reviews()
        
        if pending_contracts.empty:
            st.success("✅ No pending negotiation reviews")
        else:
            st.info(f"📊 {len(pending_contracts)} negotiations pending review")
            
            for _, contract in pending_contracts.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        st.subheader(f"Contract #{contract['contract_id']} - Deal #{contract['deal_id']}")
                    
                    with col2:
                        st.info(f"💰 ${contract.get('contract_value', 0):,}")
                    
                    # Contract details
                    st.markdown(f"**Status:** {contract.get('status', 'N/A')}")
                    st.markdown(f"**Terms:** {contract.get('contract_terms', 'N/A')}")
                    
                    # Objections
                    st.text_area(
                        "Customer Objections",
                        value=contract.get('objections', ''),
                        height=100,
                        key=f"objections_{contract['contract_id']}",
                        disabled=True
                    )
                    
                    # Proposed solutions
                    st.text_area(
                        "Proposed Solutions",
                        value=contract.get('proposed_solutions', ''),
                        height=200,
                        key=f"solutions_{contract['contract_id']}",
                        disabled=True
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve Strategy", key=f"neg_approve_{contract['contract_id']}"):
                            mark_contract_decision(contract['contract_id'], "Approved")
                            st.success("Strategy approved - contract marked as Signed!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject Strategy", key=f"neg_reject_{contract['contract_id']}"):
                            mark_contract_decision(contract['contract_id'], "Rejected")
                            st.warning("Strategy rejected - needs revision")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading negotiation reviews: {e}")


# ==============================================================================
# TAB 4: FINANCE/DUNNING REVIEW (PHASE-3 NEW)
# ==============================================================================

with tab4:
    st.header("Dunning Messages (Payment Reminders)")
    st.markdown("Review automated payment reminder emails.")
    
    try:
        pending_dunning = fetch_pending_dunning_reviews()
        
        if pending_dunning.empty:
            st.success("✅ No pending dunning reviews")
        else:
            st.info(f"📊 {len(pending_dunning)} dunning messages pending review")
            
            for _, invoice in pending_dunning.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        st.subheader(f"Invoice #{invoice['invoice_id']}")
                    
                    with col2:
                        days_overdue = invoice.get('days_overdue', 0)
                        if days_overdue > 30:
                            st.error(f"🔴 {days_overdue} days overdue")
                        elif days_overdue > 14:
                            st.warning(f"🟡 {days_overdue} days overdue")
                        else:
                            st.info(f"🔵 {days_overdue} days overdue")
                    
                    # Invoice metrics
                    col_a, col_b, col_c, col_d = st.columns(4)
                    with col_a:
                        st.metric("Amount", f"${invoice.get('amount', 0):,}")
                    with col_b:
                        st.metric("Due Date", invoice.get('due_date', 'N/A'))
                    with col_c:
                        st.metric("Dunning Stage", invoice.get('dunning_stage', 0))
                    with col_d:
                        st.metric("Confidence", f"{invoice.get('confidence_score', 0)}/100")
                    
                    # Dunning message
                    edited_dunning = st.text_area(
                        "Dunning Email Draft",
                        value=invoice.get('draft_message', ''),
                        height=250,
                        key=f"dunning_{invoice['invoice_id']}"
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve & Send", key=f"dunning_approve_{invoice['invoice_id']}"):
                            mark_dunning_decision(invoice['invoice_id'], "Approved")
                            st.success("Dunning message approved!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject", key=f"dunning_reject_{invoice['invoice_id']}"):
                            mark_dunning_decision(invoice['invoice_id'], "Rejected")
                            st.warning("Message rejected")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading dunning reviews: {e}")


# ==============================================================================
# SIDEBAR: SYSTEM HEALTH
# ==============================================================================

with st.sidebar:
    st.header("📊 System Overview")
    
    try:
        # Count pending items across all stages
        sdr_pending = len(fetch_pending_reviews())
        sales_pending = len(fetch_pending_deal_reviews())
        neg_pending = len(fetch_pending_contract_reviews())
        fin_pending = len(fetch_pending_dunning_reviews())
        
        total_pending = sdr_pending + sales_pending + neg_pending + fin_pending
        
        st.metric("Total Pending Reviews", total_pending)
        
        st.markdown("---")
        st.markdown("**By Stage:**")
        st.markdown(f"- SDR Emails: {sdr_pending}")
        st.markdown(f"- Sales Qualifications: {sales_pending}")
        st.markdown(f"- Negotiations: {neg_pending}")
        st.markdown(f"- Dunning Messages: {fin_pending}")
        
        # Refresh button
        if st.button("🔄 Refresh Dashboard"):
            st.rerun()
    
    except Exception as e:
        st.error(f"Error loading metrics: {e}")