"""
Multi-Agent Review Dashboard - FIXED VERSION

CRITICAL FIXES:
1. ORM to DataFrame conversion now properly renames 'id' field to match UI expectations
2. Safe access patterns for all ORM fields
3. Proper error handling for missing data
"""

import streamlit as st
from pathlib import Path
import sys

# Ensure project root is importable
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from app.database.db_handler import (
    # SDR functions
    fetch_pending_reviews,
    mark_review_decision,
    
    # Sales functions
    fetch_pending_deal_reviews,
    mark_deal_decision,
    
    # Negotiation functions
    fetch_pending_contract_reviews,
    mark_contract_decision,
    
    # Finance functions
    fetch_pending_dunning_reviews,
    mark_dunning_decision
)
from app.core.logging_config import configure_logging

from app.utils.validators import sanitize_text
from app.utils.orm import orm_to_df

configure_logging()


# Page config
st.set_page_config(
    page_title="Revo – Multi-Agent Review Panel",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for better styling
st.markdown("""
<style>
    .stTabs [data-baseweb="tab-list"] button [data-testid="stMarkdownContainer"] p {
        font-size: 20px;
        font-weight: 600;
    }
    .review-card {
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
        background-color: #f9f9f9;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.title("🧠 Revo – Human-in-the-Loop Review Dashboard")
st.markdown("Review AI-generated content across the entire sales pipeline.")

# Create tabs for each agent
tab1, tab2, tab3, tab4 = st.tabs(["📧 SDR Emails", "💼 Sales Qualifications", "🤝 Negotiations", "💰 Finance/Dunning"])


# ==============================================================================
# TAB 1: SDR EMAIL REVIEW
# ==============================================================================

with tab1:
    st.header("SDR Email Drafts")
    st.markdown("Review cold outreach emails generated by the SDR Agent.")
    
    try:
        # Fetch pending reviews
        pending_sdr = orm_to_df(fetch_pending_reviews(include_structural_failed=True))
        
        if pending_sdr.empty:
            st.success("✅ No pending SDR reviews")
        else:
            st.info(f"📊 {len(pending_sdr)} emails pending review")
            
            for idx, row in pending_sdr.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        # Safe field access
                        row_id = int(row.get("id", 0) or 0)
                        name = sanitize_text(row.get('name', 'Unknown'), max_len=300)
                        company = sanitize_text(row.get('company', 'Unknown'), max_len=300)
                        st.subheader(f"Lead: {name} ({company})")
                    
                    with col2:
                        # Status badge
                        review_status = row.get("review_status", "Unknown")
                        if review_status == "STRUCTURAL_FAILED":
                            st.error("❌ Validation Failed")
                        else:
                            score = row.get("confidence_score", 0) or 0
                            if score >= 85:
                                st.warning("🟡 Near Auto-Approval")
                            else:
                                st.info("🔵 Needs Review")
                    
                    # Lead details
                    col_a, col_b, col_c = st.columns(3)
                    with col_a:
                        st.metric("Role", row.get('role', 'N/A') or 'N/A')
                    with col_b:
                        st.metric("Industry", row.get('industry', 'N/A') or 'N/A')
                    with col_c:
                        score_val = row.get('confidence_score', 0) or 0
                        st.metric("Score", f"{score_val}/100")
                    
                    # Email editor
                    draft = sanitize_text(row.get("draft_message", "") or "", max_len=12000)
                    edited_email = st.text_area(
                        "Email Draft",
                        value=draft,
                        height=250,
                        key=f"sdr_email_{row_id}"
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve & Send", key=f"sdr_approve_{row_id}"):
                            mark_review_decision(row_id, "Approved", edited_email)
                            st.success("Approved!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject", key=f"sdr_reject_{row_id}"):
                            mark_review_decision(row_id, "Rejected", edited_email)
                            st.warning("Rejected")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading SDR reviews: {e}")
        st.exception(e)


# ==============================================================================
# TAB 2: SALES QUALIFICATION REVIEW
# ==============================================================================

with tab2:
    st.header("Sales Qualification Assessments")
    st.markdown("Review BANT scoring and deal qualification notes.")
    
    try:
        # FIXED: Rename 'id' to 'deal_id' for UI compatibility
        pending_deals = orm_to_df(fetch_pending_deal_reviews(), id_column_name='deal_id')
        
        if pending_deals.empty:
            st.success("✅ No pending sales reviews")
        else:
            st.info(f"📊 {len(pending_deals)} deals pending review")
            
            for idx, deal in pending_deals.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        deal_id = deal.get('deal_id', 'Unknown')
                        lead_id = deal.get('lead_id', 'Unknown')
                        company = deal.get('company', 'Unknown')
                        st.subheader(f"Deal #{deal_id} - {company} (Lead #{lead_id})")
                    
                    with col2:
                        score = deal.get('qualification_score', 0) or 0
                        if score >= 85:
                            st.success(f"🟢 Score: {score}/100")
                        elif score >= 70:
                            st.warning(f"🟡 Score: {score}/100")
                        else:
                            st.error(f"🔴 Score: {score}/100")
                    
                    # Deal metrics
                    col_a, col_b, col_c = st.columns(3)
                    with col_a:
                        st.metric("Stage", deal.get('stage', 'N/A') or 'N/A')
                    with col_b:
                        acv = deal.get('acv', 0) or 0
                        st.metric("Deal Value", f"${acv:,}")
                    with col_c:
                        st.metric("BANT Score", f"{score}/100")
                    
                    # Qualification notes
                    notes = deal.get('notes', '') or ''
                    st.text_area(
                        "Qualification Assessment",
                        value=notes,
                        height=200,
                        key=f"sales_notes_{deal_id}",
                        disabled=True  # Read-only
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve Deal", key=f"sales_approve_{deal_id}"):
                            mark_deal_decision(deal_id, "Approved")
                            st.success("Deal approved - moved to Proposal Sent!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject Deal", key=f"sales_reject_{deal_id}"):
                            mark_deal_decision(deal_id, "Rejected")
                            st.warning("Deal rejected")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading sales reviews: {e}")
        st.exception(e)


# ==============================================================================
# TAB 3: NEGOTIATION REVIEW
# ==============================================================================

with tab3:
    st.header("Negotiation Strategies")
    st.markdown("Review objection handling and proposed solutions.")
    
    try:
        # FIXED: Rename 'id' to 'contract_id' for UI compatibility
        pending_contracts = orm_to_df(fetch_pending_contract_reviews(), id_column_name='contract_id')
        
        if pending_contracts.empty:
            st.success("✅ No pending negotiation reviews")
        else:
            st.info(f"📊 {len(pending_contracts)} negotiations pending review")
            
            for idx, contract in pending_contracts.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        contract_id = contract.get('contract_id', 'Unknown')
                        deal_id = contract.get('deal_id', 'Unknown')
                        st.subheader(f"Contract #{contract_id} - Deal #{deal_id}")
                    
                    with col2:
                        value = contract.get('contract_value', 0) or 0
                        st.info(f"💰 ${value:,}")
                    
                    # Contract details
                    status = contract.get('status', 'N/A') or 'N/A'
                    terms = contract.get('contract_terms', 'N/A') or 'N/A'
                    st.markdown(f"**Status:** {status}")
                    st.markdown(f"**Terms:** {terms}")
                    
                    # Objections
                    objections = contract.get('objections', '') or ''
                    st.text_area(
                        "Customer Objections",
                        value=objections,
                        height=100,
                        key=f"objections_{contract_id}",
                        disabled=True
                    )
                    
                    # Proposed solutions
                    solutions = contract.get('proposed_solutions', '') or ''
                    st.text_area(
                        "Proposed Solutions",
                        value=solutions,
                        height=200,
                        key=f"solutions_{contract_id}",
                        disabled=True
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve Strategy", key=f"neg_approve_{contract_id}"):
                            mark_contract_decision(contract_id, "Approved")
                            st.success("Strategy approved - contract marked as Signed!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject Strategy", key=f"neg_reject_{contract_id}"):
                            mark_contract_decision(contract_id, "Rejected")
                            st.warning("Strategy rejected - needs revision")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading negotiation reviews: {e}")
        st.exception(e)


# ==============================================================================
# TAB 4: FINANCE/DUNNING REVIEW
# ==============================================================================

with tab4:
    st.header("Dunning Messages (Payment Reminders)")
    st.markdown("Review automated payment reminder emails.")
    
    try:
        # FIXED: Rename 'id' to 'invoice_id' for UI compatibility
        pending_dunning = orm_to_df(fetch_pending_dunning_reviews(), id_column_name='invoice_id')
        
        if pending_dunning.empty:
            st.success("✅ No pending dunning reviews")
        else:
            st.info(f"📊 {len(pending_dunning)} dunning messages pending review")
            
            for idx, invoice in pending_dunning.iterrows():
                with st.container():
                    col1, col2 = st.columns([3, 1])
                    
                    with col1:
                        invoice_id = invoice.get('invoice_id', 'Unknown')
                        st.subheader(f"Invoice #{invoice_id}")
                    
                    with col2:
                        days_overdue = invoice.get('days_overdue', 0) or 0
                        if days_overdue > 30:
                            st.error(f"🔴 {days_overdue} days overdue")
                        elif days_overdue > 14:
                            st.warning(f"🟡 {days_overdue} days overdue")
                        else:
                            st.info(f"🔵 {days_overdue} days overdue")
                    
                    # Invoice metrics
                    col_a, col_b, col_c, col_d = st.columns(4)
                    with col_a:
                        amount = invoice.get('amount', 0) or 0
                        st.metric("Amount", f"${amount:,}")
                    with col_b:
                        due_date = invoice.get('due_date', 'N/A') or 'N/A'
                        st.metric("Due Date", str(due_date))
                    with col_c:
                        stage = invoice.get('dunning_stage', 0) or 0
                        st.metric("Dunning Stage", stage)
                    with col_d:
                        confidence = invoice.get('confidence_score', 0) or 0
                        st.metric("Confidence", f"{confidence}/100")
                    
                    # Dunning message
                    draft = invoice.get('draft_message', '') or ''
                    edited_dunning = st.text_area(
                        "Dunning Email Draft",
                        value=draft,
                        height=250,
                        key=f"dunning_{invoice_id}"
                    )
                    
                    # Action buttons
                    btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 4])
                    
                    with btn_col1:
                        if st.button("✅ Approve & Send", key=f"dunning_approve_{invoice_id}"):
                            mark_dunning_decision(invoice_id, "Approved")
                            st.success("Dunning message approved!")
                            st.rerun()
                    
                    with btn_col2:
                        if st.button("❌ Reject", key=f"dunning_reject_{invoice_id}"):
                            mark_dunning_decision(invoice_id, "Rejected")
                            st.warning("Message rejected")
                            st.rerun()
                    
                    st.markdown("---")
    
    except Exception as e:
        st.error(f"Error loading dunning reviews: {e}")
        st.exception(e)


# ==============================================================================
# SIDEBAR: SYSTEM HEALTH
# ==============================================================================

with st.sidebar:
    st.header("📊 System Overview")
    
    try:
        # Count pending items across all stages
        sdr_pending = len(fetch_pending_reviews())
        sales_pending = len(fetch_pending_deal_reviews())
        neg_pending = len(fetch_pending_contract_reviews())
        fin_pending = len(fetch_pending_dunning_reviews())
        
        total_pending = sdr_pending + sales_pending + neg_pending + fin_pending
        
        st.metric("Total Pending Reviews", total_pending)
        
        st.markdown("---")
        st.markdown("**By Stage:**")
        st.markdown(f"- SDR Emails: {sdr_pending}")
        st.markdown(f"- Sales Qualifications: {sales_pending}")
        st.markdown(f"- Negotiations: {neg_pending}")
        st.markdown(f"- Dunning Messages: {fin_pending}")
        
        # Refresh button
        if st.button("🔄 Refresh Dashboard"):
            st.rerun()
    
    except Exception as e:
        st.error(f"Error loading metrics: {e}")
